# Generated by Django 3.0.7 on 2020-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RdpLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_name', models.CharField(max_length=250)),
                ('vm_username', models.CharField(max_length=250)),
                ('vm_password', models.CharField(max_length=50)),
                ('labtype', models.CharField(choices=[('rdp', 'RDP'), ('ssh', 'SSH')], default='rdp', max_length=6)),
                ('rdp_file', models.FileField(upload_to='labimage/')),
            ],
        ),
        migrations.CreateModel(
            name='UrlLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
